### ISSUE TITLE
inducción Matematica

### ISSUE THREAD

**Issue by Maritza2893** [SistemasTecTlaxiaco/actividad-9-practica-de-inducci-n-matem-tica-2363#1]
[Problema 3.pdf](https://github.com/SistemasTecTlaxiaco/actividad-9-practica-de-inducci-n-matem-tica-2363/files/13225351/Problema.3.pdf)

**Comment by JoseRodriguez-23620213** [comment]
Portada 25
Procedimiento: 22
Figuras: 25
Resultado 25
Total: 97 Cal.Final: 19.4

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
