### ISSUE TITLE
Mapas

### ISSUE THREAD

**Issue by Maritza2893** [SistemasTecTlaxiaco/actividad-9-practica-de-inducci-n-matem-tica-2363#3]
[Mapas de Karnaugh.pdf](https://github.com/SistemasTecTlaxiaco/actividad-9-practica-de-inducci-n-matem-tica-2363/files/13609287/Mapas.de.Karnaugh.pdf)

**Comment by josealfredo79** [comment]
Falto con la simulacion..Revisado..
